### ISSUE TITLE
lime-suite: namespaces for public headers

### ISSUE THREAD

**Issue by guruofquality** [limemicro/lms7suite#10]
This might be more of a matter of taste, but since the lime-suite is largely C++, we might want to put namespace lime {} around classes and enums found in public headers. There should not be many changes to the code-base. The implementation cpp files would gain the line ```using namespace lime```, and the headers would gain the line ```namespace lime {``` and a closing bracked ```}```.

**Comment by rjonaitis** [comment]
Some enumerations were clashing with CyAPI on windows, so I added lime namespace to all control logic files.

**Comment by guruofquality** [comment]
Looks pretty good. We can always add more namespace lime if something is missing. I guess we can close out this issue then :-)
