### ISSUE TITLE
Does not support use with lower frequencies.

### ISSUE THREAD

**Issue by 9600** [limemicro/lms7suite#30]
E.g.

$ osmocom_fft -F -a "driver=lime,soapy=0,clock=40e6,cacheCalibrations=1" -s 5e6 -f 7e6

Results in:

LMS_StreamBoard::ConfigurePLL(tx=10MHz, rx=5MHz)
C[INFO] SoapyLMS7::setFrequency(Rx, 0, RF, 7.000000 MHz), ref 30.720000 MHz
[INFO] SoapyLMS7::setFrequency(Rx, 0, BB, -1897.655000 MHz), ref 30.720000 MHz

See also attached for FFT frequency scale displayed.
![030316_gr-fosphor_7mhz](https://cloud.githubusercontent.com/assets/233314/13531201/3a5cd606-e21d-11e5-9c68-e2a6ef519eb4.png)

**Comment by guruofquality** [comment]
>> So I think SetFrequencySX() or GetFrequencySX_MHz() didn't handle 7MHz correctly.

> Correct, these functions configure only Rx/Tx PLL frequencies, and they
can't be configured that low. To achieve 7 MHz frequency additional chip
configuring is required. Perhaps a higher level function should be created
to handle all that.

So I think the call to set the RF frequency needs to clip the requested frequency to the closest possible frequency. When that happens, the default tuning algorithm in SoapySDR will automatically compensate for the error using the CORDIC.

If for some reason we don't like that automatic behaviour with the clipping and cordic correction outside of the driver, then SoapySDR::setFrequency(dir, chan, freq){} can be overloaded to implement something smart as well.

Is that basically the right idea here? And what is the actual/achievable lower bound that the LO can tune?

**Comment by 9600** [comment]
@guruofquality are you suggesting that applications would have to do something different with this particular hardware at lower frequencies? That doesn't sound right.

@rjonaitis could you comment on LO bounds.

**Comment by guruofquality** [comment]
> @guruofquality are you suggesting that applications would have to do something different with this particular hardware at lower frequencies? That doesn't sound right.

Nope, just driver related work in lms7suite. The SoapyLime::setFrequency() call will just need to clip the target frequency to a possible frequency.

It probably gets a bit hairy to tune near the lower VCO band edge, so we might need a slightly conservative lower bound, and I think it might be a function of the clock rate.

**Comment by guruofquality** [comment]
FWIW, I have been using fixed (100e3, 3.8e9) as the tunable LO range in the LMS7002M. I may have pulled that from the data sheet rather than testing edge cases. I also added this as an API call to add to the LMS700M class, so if its configurable, that can be added like getSXXRange(): https://github.com/limemicro/lms7suite/issues/15

**Comment by rjonaitis** [comment]
> could you comment on LO bounds.

PLLs can be tuned from around 30 MHz to 3.8 GHz

**Comment by guruofquality** [comment]
This should do the trick: https://github.com/limemicro/lms7suite/commit/27b488b75bfb55339f828f120b8617d50c57de8b
