### ISSUE TITLE
libusbx warnings.

### ISSUE THREAD

**Issue by 9600** [limemicro/lms7suite#35]
Frequently get libusbx warnings of the sort:

2016-03-20 12:34:15 ::1: libusbx: warning [handle_timeout] async cancel failed -5 errno=22

E.g. when using PothosGui and changing settings or deactivating a topology.

**Comment by guruofquality** [comment]
I think these are prints from when the worker threads are stopped. There are actually more prints, but they are commented out. If we ever isolate the worker threads from the calibration, then you will see these a lot less -- like once at shutdown.

**Comment by guruofquality** [comment]
Another data point: After stopping the topology, I also saw this print continually. In this case the rx thread is still running, which is probably the source. But not sure why. It didn't affect anything from bring re-activated properly.
